name: "[Doc][A] Build Only"

on:
  push:
    branches:
      - "**"

jobs:
  build-docusaurus:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.13.6", binary-version: "2.13", java-version: "11", java-distribution: "temurin" }
        node:
          - { version: "16.16.0" }

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.scala.java-version }}
          distribution: ${{ matrix.scala.java-distribution }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache SBT
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: Cache npm
        uses: actions/cache@v3.0.11
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node.version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node.version }}

      - name: Render markdown and build website
        run: |
          sbt \
            ++${{ matrix.scala.version }}! \
            clean \
            docs/mdoc \
            docs/docusaurGenerateAlgoliaConfigFile \
            docs/docusaurGenerateGoogleAnalyticsConfigFile \
            docs/docusaurInstall \
            docs/docusaurCleanBuild \
            docs/docusaurBuild
